apiVersion: v1
kind: Template
metadata:
  name: jenkins-jos
labels:
  template: jenkins-jos
  group: jenkins-jos
metadata:
  annotations:
    description: Maakt een CI/CD omgeving met Jenkins
    iconClass: icon-jenkins
  name: jenkins-jos
objects:
# Jenkins
- apiVersion: v1
  kind: Route
  metadata:
    name: jenkins-route
  spec:
    port:
      targetPort: 8080 
    to:
      kind: Service
      name: jenkins-jos
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "jenkins-jos"
  spec:
    template:
      metadata:
        labels:
          app: "jenkins-jos"
      spec:
        containers:
          - name: "jenkins-jos"
            image: "jos/jenkins-jos"
            ports:
              - containerPort: 8080
                protocol: "TCP"
    replicas: 1
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - "jenkins-jos"
          from:
            kind: "ImageStreamTag"
            namespace: "jos"
            name: "jenkins-jos:2.7"
    strategy:
      type: "Rolling"
      paused: false
      revisionHistoryLimit: 1
      minReadySeconds: 0
- apiVersion: v1
  kind: Service
  metadata:
    name: jenkins-jos
  spec:
    selector:
      app: jenkins-jos
    ports:
      -
        port: 8080
        protocol: TCP
        targetPort: 8080


