kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "jenkins-jos"
spec:
  template:
    metadata:
      labels:
        name: "jenkins-jos"
    spec:
      containers:
        - name: "jenkins-jos"
          image: "jos/jenkins-jos"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 1
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - "jenkins-jos"
        from:
          kind: "ImageStreamTag"
          namespace: "jos"
          name: "jenkins-jos:2.7"
  strategy:
    type: "Rolling"
    paused: false
    revisionHistoryLimit: 1
    minReadySeconds: 0
